config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'notes#show'
  get '/signup', to:'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  get '/post_list', to: 'users#show'
  get '/post', to: 'notes#new'
  get '/note', to: 'notes#post_notes'
  get '/note_buy', to: 'notes#buy_note'
  patch '/note_buy', to: 'notes#buy_note_create'
  get  '/images', to: 'images#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :notes,          only: [:create, :destroy,:buy_note]
  resources :relationships,       only: [:create, :destroy]
  resources :images, only:[:create]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div>
    <div>
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_header.html.erb
<div class="container">
<nav class="navbar navbar-light justify-content-between">
  <%= link_to "NEMNOTE", root_path,class:"navbar-brand"  %>
  <div class="row">
  <% if logged_in? %>
      <%= link_to "記事一覧", root_path,class: "btn btn-outline-success ml-1 my-2 my-sm-0" %>
      <%= link_to "マイページ", user_path(current_user),class: "btn btn-outline-success ml-1 my-2 my-sm-0" %>
      <%= link_to "情報編集", edit_user_path(current_user),class: "btn btn-outline-success ml-1 my-2 my-sm-0" %>
      <%= link_to "記事投稿", post_path,class: "btn btn-outline-success ml-1 my-2 my-sm-0" %>
      <%= link_to "ログアウト", logout_path, method: :delete ,class: "btn btn-outline-success ml-1 my-2 my-sm-0" %>
    <% else %>
      <%= link_to "ログイン", login_path, class: "btn btn-outline-success ml-1 my-2 my-sm-0" %>
      <%= link_to "新規登録", signup_path, class: "btn btn-outline-success ml-1 my-2 my-sm-0"  %>
<% end %>
  </div>
</nav>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>